name: automl-api
channels:
  - conda-forge
dependencies:
  - python=3.12
  - fastapi
  - fastapi-users
  - uuid6
  - structlog
  - python-dotenv
  - psycopg
  - sqlalchemy
  - sqlalchemy-utils
  - pydantic
  - sqlmodel
  - uvicorn
  - sqlacodegen
  - alembic
  - strawberry-graphql
  - pycaret
  - rdkit
  - sentry-sdk
  - black
  - ruff
  - mypy
  - tox
  - factory_boy
  - pytest
  - pytest-factoryboy
  - pytest-randomly
  - pytest-cov
  - mkdocs
